country2adj = {'Albania': 'Albanian',
'Algeria': 'Algerian',
'Australia': 'Australian',
'Austria': 'Austrian',
'Belarus': 'Belarusian',
'Belgium': 'Belgian',
'Brazil': 'Brazilian',
'Burkina Faso':	'Burkina Faso',
'Canada': 'Canadian',
'China': 'Chinese',
'Croatia': 'Croatian',
'Czech Republic': 'Czech',
'Denmark': 'Danish',
'Finland': 'Finnish',
'France': 'French',
'Germany': 'German',
'Greece': 'Greek',
'Indonesia': 'Indonesian',
'Israel': 'Israeli',
'Italy': 'Italian',
'Japan': 'Japanese',
'Latvia': 'Latvian',
'Lithuania': 'Lithuanian',
'Malaysia': 'Malaysian',
'Mauritania': 'Mauritanian',
'Morocco': 'Moroccan',
'Netherlands': 'Dutch',
'Pakistan': 'Pakistani',
'Poland': 'Polish',
'Russia': 'Russian',
'Saudi Arabia':	'Saudi Arabian',
'Serbia': 'Serbian',
'Singapore': 'Singaporean',
'Slovakia': 'Slovakian',
'Slovenia': 'Slovenian',
'South Korea': 'South Korean',
'Spain': 'Spanish',
'Sweden': 'Swedish',
'Switzerland': 'Swiss',
'Taiwan': 'Taiwanese',
'Turkey': 'Turkish',
'Ukraine': 'Ukrainian',
'United Kingdom': 'British',
'United States of America': 'American',
'Venezuela': 'Venezuelan',
'Vietnam': 'Vietnamese',
'Zambia': 'Zambian'}